version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports: 
      - '9090:9090'
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus/data
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /data/prometheus:/prometheus
      - ./endpoints:/etc/prometheus/endpoints
      # - prometheus:/prometheus/data
    # depends_on: 
    #  - cadvisor
    #  - node-exporter
    #  - pushgateway
    networks: 
      - wwatch

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    expose: 
      - 9100
    # ports:
      # - '9100:9100'   # 暂不映射
    networks:
      - wwatch

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - '9091:9091'
    networks:
      - wwatch

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    expose:
      - 8080
    # ports:
      # - '8080:8080'   # 暂不映射
    networks: 
      - wwatch
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: 
      - '3000:3000'
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - wwatch
    volumes:
      - /data/grafana:/var/lib/grafana
      # - grafana:/var/lib/grafana

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - '9000:9000'
    networks: 
      - wwatch
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks: 
  wwatch:
    name: wwatch-net
    driver: bridge
    attachable: true

volumes:
  # grafana:
    # name: grafana-data      # 权限问题，转用 mount
  # prometheus:
    # name: prometheus-data
  portainer:
    name: portainer-data