global:
  scrape_interval: 5s           # how frequently to scrape targeets by default
  scrape_timeout: 5s            # how long until a scrape requests time out
  evaluation_interval: 1m       # how frequently to evaluate rules
  external_labels:
    monitor: wwatch

# rules_files:
# [ - <filepath_glob> ... ]

scrape_configs:
  - job_name: prometheus
    file_sd_configs:
      - files:
        - ./endpoints/prometheus-endpoints.json
  - job_name: node
    file_sd_configs:
      - files:
        - ./endpoints/node-endpoints.json
        refresh_interval: 3m
  - job_name: cadvisor
    file_sd_configs:
      - files:
        - ./endpoints/cadvisor-endpoints.json
        refresh_interval: 3m
  - job_name: scrapy
    file_sd_configs:
      - files:
        - ./endpoints/scrapy-endpoints.json
        refresh_interval: 3m
